newWebhook: New Webhook
webhookCreated: Webhook created successfully
webhookUpdated: Webhook updated successfully
webhookDeleted: Webhook deleted successfully
triggers:
  artifactCreation: 制品 Creation
  artifactDeletion: 制品 Deletion
  artifactModification: 制品 Modification
table:
  columns:
    name: Webhook
    trigger: 事件
  noWebhooksTitle: There are no webhooks available
formFields:
  name: 名称
  id: Id
  description: 描述
  url: Payload URL
  secret: 密钥
  triggerLabel: Which events do you like to trigger this webhook?
  allTrigger: Send me everything
  customTrigger: Let me select individual events
  SSLVerification: SSL Verification
  enableSSLVerification: Enable SSL Verification
  advanced: Advanced
  extraHeader: 密钥
  extraHeaderPlaceholder: Enter Header
  extraValue: Value
  extraValuePlaceholder: Enter Value
  addNewKeyValuePair: Add New 密钥 Value Pair
  enabled: 已启用
deleteModal:
  title: 删除 Webhook
  message: Are you sure you want to delete this webhook?
